/*
 * Main.java
 */
package net.ausiasmarch.examen.gui;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import net.ausiasmarch.common.Convert;
import net.ausiasmarch.examen.modelo.*;

/**
 *
 * @author Administrador
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private SeguroMedico seguroMedico;

    public Main() {
        initComponents();

        setSize(620, 350);
        setLocationRelativeTo(null);

        seguroMedico = new SeguroMedico();

        //Limpiar los datos
        jTextFieldEdad.setText("");
        jTextFieldImporteAnual.setText("");
        jTextFieldImporteMensual.setText("");
        jTextFieldNumHijos.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSexo = new javax.swing.ButtonGroup();
        jLabelEdad = new javax.swing.JLabel();
        jTextFieldEdad = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jCheckBoxCoberturaCorazon = new javax.swing.JCheckBox();
        jCheckBoxCoberturaInVitro = new javax.swing.JCheckBox();
        jCheckBoxCoberturaDermatologia = new javax.swing.JCheckBox();
        jCheckBoxPediatria = new javax.swing.JCheckBox();
        jCheckBoxCoberturaOftalmologia = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jCheckBoxEnfermedadCorazon = new javax.swing.JCheckBox();
        jCheckBoxEnfermedadOjos = new javax.swing.JCheckBox();
        jCheckBoxEnfermedadPiel = new javax.swing.JCheckBox();
        jCheckBoxCasado = new javax.swing.JCheckBox();
        jTextFieldNumHijos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCheckBoxEmbarazada = new javax.swing.JCheckBox();
        jButtonCalcular = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldImporteAnual = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jRadioButtonHombre = new javax.swing.JRadioButton();
        jRadioButtonMujer = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxTrabajo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldImporteMensual = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Contratación de Seguro Médico");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEdad.setText("Edad:");
        getContentPane().add(jLabelEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, 25));
        getContentPane().add(jTextFieldEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 22, 70, 20));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Coberturas Ampliadas"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBoxCoberturaCorazon.setText("Corazón");
        jPanel1.add(jCheckBoxCoberturaCorazon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jCheckBoxCoberturaInVitro.setText("Fecundación in vitro");
        jPanel1.add(jCheckBoxCoberturaInVitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jCheckBoxCoberturaDermatologia.setText("Dermatología");
        jPanel1.add(jCheckBoxCoberturaDermatologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        jCheckBoxPediatria.setText("Pediatría");
        jPanel1.add(jCheckBoxPediatria, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jCheckBoxCoberturaOftalmologia.setText("Oftalmología");
        jPanel1.add(jCheckBoxCoberturaOftalmologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 590, 60));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()), "Enfermedades"));

        jCheckBoxEnfermedadCorazon.setText("Corazón");

        jCheckBoxEnfermedadOjos.setText("Ojos");

        jCheckBoxEnfermedadPiel.setText("Piel");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jCheckBoxEnfermedadCorazon)
                .addGap(138, 138, 138)
                .addComponent(jCheckBoxEnfermedadOjos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(jCheckBoxEnfermedadPiel)
                .addGap(91, 91, 91))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxEnfermedadCorazon)
                    .addComponent(jCheckBoxEnfermedadOjos)
                    .addComponent(jCheckBoxEnfermedadPiel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 106, 590, 60));

        jCheckBoxCasado.setText("Casado/a");
        getContentPane().add(jCheckBoxCasado, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));
        getContentPane().add(jTextFieldNumHijos, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 22, 40, 20));

        jLabel2.setText("Nº Hijos:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 70, 25));

        jCheckBoxEmbarazada.setText("Embarazada");
        getContentPane().add(jCheckBoxEmbarazada, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        jButtonCalcular.setText("Calcular");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 100, -1));

        jLabel4.setText("Importe Anual:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, 20));

        jTextFieldImporteAnual.setEditable(false);
        jTextFieldImporteAnual.setBackground(new java.awt.Color(153, 255, 153));
        jTextFieldImporteAnual.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(jTextFieldImporteAnual, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 110, 20));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(" Sexo "));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroupSexo.add(jRadioButtonHombre);
        jRadioButtonHombre.setSelected(true);
        jRadioButtonHombre.setText("Hombre");
        jPanel5.add(jRadioButtonHombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        buttonGroupSexo.add(jRadioButtonMujer);
        jRadioButtonMujer.setText("Mujer");
        jPanel5.add(jRadioButtonMujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 60));

        jLabel10.setText("Trabajo:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, 20));

        jComboBoxTrabajo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Funcionario", "Contratado", "Autónomo" }));
        getContentPane().add(jComboBoxTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 130, -1));

        jLabel7.setText("€");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 10, 20));

        jLabel5.setText("Importe Mensual:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, 20));

        jTextFieldImporteMensual.setEditable(false);
        jTextFieldImporteMensual.setBackground(new java.awt.Color(153, 255, 153));
        jTextFieldImporteMensual.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(jTextFieldImporteMensual, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 90, 20));

        jLabel8.setText("€");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 10, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed

        //crear nuevas variables de tipo DOUBLE
        double importeAnual, importeMensual;
        //crear nuevas variables tipo INT
        int edad, numHijos;
        //Validacion para que avise si no hay nada escrito (EMPTY = VACIO)
        if (jTextFieldEdad.getText().isEmpty()) {
            mensaje("Introduce una edad");
            return;
        }
        //Validacion para que avise si no hay nada escrito (EMPTY = VACIO)
        if (jTextFieldNumHijos.getText().isEmpty()) {
            mensaje("Introduce un numero de hijo");
            return;
        }
        // Para que sea valido el numero, solo NUMERO,NO LETRAS ni SIMBOLOS
        if (!Convert.isValidInt(jTextFieldEdad.getText())) {
            mensaje("Introduce una edad valida");
            return;
        }
         // Para que sea valido el numero, solo NUMERO,NO LETRAS ni SIMBOLOS          
        if (!Convert.isValidInt(jTextFieldNumHijos.getText())) {
            mensaje("Introduce un numero de hijos valido");
            return;
        }

     //Convertir a los datos de entrada a los tipos adecuados
     //parseINT --> porque es un numero entero 
        edad = Convert.parseInt(jTextFieldEdad.getText());
        numHijos = Convert.parseInt(jTextFieldNumHijos.getText());
        
     //Pasar todos los datos a la clase SeguroMedico con set (edad, num hijos, RadioButton, JCheckBox, ComboBox)
        seguroMedico.setEdad(edad);
        seguroMedico.setNumHijos(numHijos);
        seguroMedico.setHombre(jRadioButtonHombre.isSelected());
        seguroMedico.setMujer(jRadioButtonMujer.isSelected());
        seguroMedico.setTrabajo(jComboBoxTrabajo.getSelectedItem().toString());
        seguroMedico.setCasado(jCheckBoxCasado.isSelected());
        seguroMedico.setEmbarazada(jCheckBoxEmbarazada.isSelected());
        seguroMedico.setCoberturaCorazon(jCheckBoxCoberturaCorazon.isSelected());
        seguroMedico.setCoberturaDermatologia(jCheckBoxCoberturaDermatologia.isSelected());
        seguroMedico.setCoberturaInVitro(jCheckBoxCoberturaInVitro.isSelected());
        seguroMedico.setCoberturaOftalmologica(jCheckBoxCoberturaOftalmologia.isSelected());
        seguroMedico.setCoberturaPediatria(jCheckBoxPediatria.isSelected());
        seguroMedico.setEnfermedadCorazon(jCheckBoxEnfermedadCorazon.isSelected());
        seguroMedico.setEnfermedadOjos(jCheckBoxEnfermedadOjos.isSelected());
        seguroMedico.setEnfermedadPiel(jCheckBoxEnfermedadPiel.isSelected());
        
        // Mostrar si se acepta el seguro médico 
        //y en caso de que no se acepte, mostrar el mensaje devuelto por la
        //clase SeguroMedico
        
        if(seguroMedico.aceptado() == false){
            //mensaje esta en SEGUROMEDICO con GET/SET y en los IF
            mensaje(seguroMedico.getMensaje());
            return;
        }

       //Obtener los datos de los importes y mostrarlos dándoles el formato apropiado
        importeMensual = seguroMedico.importeMensual();
        importeAnual = seguroMedico.importeAnual();
        
        //Mostrarlos dandole formato apropiado:
        jTextFieldImporteMensual.setText(Convert.format(importeMensual, 2));
        jTextFieldImporteAnual.setText(Convert.format(importeAnual, 2));
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void mensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            String look = UIManager.getSystemLookAndFeelClassName();
            javax.swing.UIManager.setLookAndFeel(look);
            /*
             for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
             if (info.getName().equals(("Nimbus"))) {
             javax.swing.UIManager.setLookAndFeel(info.getClassName());
             break;
             }
             }
             */

        } catch (ClassNotFoundException | InstantiationException |
                IllegalAccessException | UnsupportedLookAndFeelException ex) {
            throw new RuntimeException(ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupSexo;
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JCheckBox jCheckBoxCasado;
    private javax.swing.JCheckBox jCheckBoxCoberturaCorazon;
    private javax.swing.JCheckBox jCheckBoxCoberturaDermatologia;
    private javax.swing.JCheckBox jCheckBoxCoberturaInVitro;
    private javax.swing.JCheckBox jCheckBoxCoberturaOftalmologia;
    private javax.swing.JCheckBox jCheckBoxEmbarazada;
    private javax.swing.JCheckBox jCheckBoxEnfermedadCorazon;
    private javax.swing.JCheckBox jCheckBoxEnfermedadOjos;
    private javax.swing.JCheckBox jCheckBoxEnfermedadPiel;
    private javax.swing.JCheckBox jCheckBoxPediatria;
    private javax.swing.JComboBox jComboBoxTrabajo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButtonHombre;
    private javax.swing.JRadioButton jRadioButtonMujer;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldImporteAnual;
    private javax.swing.JTextField jTextFieldImporteMensual;
    private javax.swing.JTextField jTextFieldNumHijos;
    // End of variables declaration//GEN-END:variables

}
